// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAh2b3qym8VlaMOKpdu-wgriELKp4L2vr4',
    appId: '1:999927847051:web:26d438af6f29bfd9e49c8e',
    messagingSenderId: '999927847051',
    projectId: 'call-distribution',
    authDomain: 'call-distribution-74c56.firebaseapp.com',
    storageBucket: 'call-distribution.appspot.com',
    measurementId: 'G-VMS60NPJ7Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChKTDCwEL9usbmilFgyA2gdycmaoJ2yyo',
    appId: '1:999927847051:android:d59af202f58ee96ce49c8e',
    messagingSenderId: '999927847051',
    projectId: 'call-distribution',
    storageBucket: 'call-distribution.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIv5rPcCgnDg5LOwyK-7vEv5oGeEUdQ9o',
    appId: '1:999927847051:ios:3f868575c3966228e49c8e',
    messagingSenderId: '999927847051',
    projectId: 'call-distribution',
    storageBucket: 'call-distribution.appspot.com',
    iosBundleId: 'com.example.tiktokFlutterClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIv5rPcCgnDg5LOwyK-7vEv5oGeEUdQ9o',
    appId: '1:999927847051:ios:65d1371795d4b71be49c8e',
    messagingSenderId: '999927847051',
    projectId: 'call-distribution',
    storageBucket: 'call-distribution.appspot.com',
    iosBundleId: 'com.example.tiktokFlutterClone.RunnerTests',
  );
}
