# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "android for distribution"
  lane :firebase_distribution do
    sh"flutter clean"
    sh "flutter build apk --flavor Production -t lib/main_production.dart"
    firebase_app_distribution(
      app: "1:999927847051:android:d59af202f58ee96ce49c8e",
      firebase_cli_token: "1//033aNoMbV8rvtCgYIARAAGAMSNwF-L9Ir7VQCDbXksVGeCcq9UH9rrWFwIbaG7ER4-_B-R5NDGJfNo3wSxn0A3hzRXmbGqI-d_ms",
      android_artifact_type:"APK",
      android_artifact_path:"../build/app/outputs/flutter-apk/app-production-release.apk",
      testers:"bbasimsalah@gmail.com,mohamadgazer96@gmail.com",
      release_notes:"first fastlane distributions"
    )
  end
end
# run fastlane android firebase_distribution

